
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: dbacontrol_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  


test:
  <<: *default
  database: dbacontrol_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: dbacontrol_production
    username: dbacontrol
    password: <%= ENV["DBACONTROL_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: dbacontrol_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: dbacontrol_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: dbacontrol_production_cable
    migrations_paths: db/cable_migrate
